name: Deploy JAR to Tomcat

on:

  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to deploy'
        required: true
        default: 'my-app-1.0.0.jar'

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0  # Specify the Terraform version you need

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: ./iac/terraform # Change this to the path of your Terraform configuration
      run: terraform apply -auto-approve
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download JAR from Artifactory
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        REPO_PATH: ${{ secrets.REPO_PATH }}
        ARTIFACT_NAME: ${{ secrets.ARTIFACT_NAME }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |

        ./scripts/deploy.sh $ARTIFACTORY_URL $REPO_PATH $ARTIFACT_NAME $ARTIFACTORY_USERNAME $ARTIFACTORY_PASSWORD

        # curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
        #   -O $ARTIFACTORY_URL/$REPO_PATH/$ARTIFACT_NAME

    - name: Deploy JAR to Tomcat server
      env:
        TOMCAT_SERVER: ${{ secrets.TOMCAT_SERVER }}
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        ARTIFACT_NAME: ${{ secrets.ARTIFACT_NAME }}
      run: |
        scp -o StrictHostKeyChecking=no $ARTIFACT_NAME $TOMCAT_USER@$TOMCAT_SERVER:/path/to/tomcat/webapps/
        ssh -o StrictHostKeyChecking=no $TOMCAT_USER@$TOMCAT_SERVER "sh /path/to/tomcat/bin/shutdown.sh && sh /path/to/tomcat/bin/startup.sh"
